### ISSUE TITLE
Shorten author name list

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/mpox#290]
Right now the author name list is very long, causing deteriorated functionality:
<img width="1088" alt="Brave Browser 2024-11-16 15 06 08" src="https://github.com/user-attachments/assets/12e17831-3655-49a2-a91d-1715cd0e18af">

We should shorten with e.g. augur curate's functionality for shortening author names.

**Comment by joverlee521** [comment]
_@genehack asked a similar question for yellow fever on [Slack](https://bedfordlab.slack.com/archives/C0K3GS3J8/p1732056326455449), so summarizing discussion here_

We already abbreviate authors as part of the ingest [curate rule](https://github.com/nextstrain/mpox/blob/af33cf20536e0b8c2bc9d7dc8d17ea5861730c31/ingest/rules/curate.smk#L90-L93) and output as the `abbr_authors` column. However, the full authors list is being used in the final Auspice output because `augur export v2` is hard-coded to check for the `author` or `authors` field ([ref](https://github.com/nextstrain/augur/blob/55508a30c26b9e6fdcafd009552bae7963fbe685/augur/export_v2.py#L682-L688)). 

Outside of updating augur export, the best path forward would be to switch `authors` to `full_authors` and `abbr_authors` to `authors`. Example in [pathogen-repo-guide](https://github.com/nextstrain/pathogen-repo-guide/commit/7bdb45de7e78fd717f8e14b7083bc37277cf3df4)

**Comment by corneliusroemer** [comment]
Switching sounds good to me.

We should probably unhardcode authors in export though eventually.

**Comment by jameshadfield** [comment]
> We should probably unhardcode authors in export though eventually.

Yes. My memory was that we used "authors" (in metadata TSVs) to represent "Roemer et al" etc, and `augur export` was designed around that. We've since switched to encoding the entire author list as "authors" without updating `augur export`.

**Comment by genehack** [comment]
☝️ created [issue in augur repo](https://github.com/nextstrain/augur/issues/1685) for removing the hard-coded export.
